#!/usr/bin/env python

import argparse, syslog

from appletlib.app      import Application
from sysstatapplet.cpu  import IndicatorCpu
from sysstatapplet.mem  import IndicatorMem
from sysstatapplet.disk import IndicatorDisk

def parseCommandLine():
    ret = {}
    parser = argparse.ArgumentParser(
        description='Sysstat applet collection')
    parser.add_argument( '-d', '--daemon',
                         help='run as daemon', action="store_true")
    parser.add_argument( '-v', '--verbosity', type=int, default=0,
                         help='select verbosity (default: 0)')
    args = parser.parse_args()
    
    # detach immediately if run as daemon
    if args.daemon: Application.detach()
    
    ret['verbosity'] = args.verbosity
    ret['daemon']    = args.daemon
    
    return ret

def main():
    argdict = parseCommandLine()
    app = Application("mechnich","sysstat-applet")
    app.init(argdict)
    i = [IndicatorCpu(), IndicatorMem(), IndicatorDisk()]
    syslog.syslog( syslog.LOG_INFO, "INFO   startup complete");
    return app.exec_()

if __name__ == "__main__":
    main()
